server:
  port: 8772

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

#data:
#  env: NaN
#  user:
#    username: NaN
#    password: NaN